### ISSUE TITLE
error in yarn install

### ISSUE THREAD

**Issue by hex0cter** [klarna/ui#443]
I got the following error when I ran ```yarn```:

```
~/git/klarna/ui(master ✔) yarn
yarn install v1.1.0
[1/4] 🔍   Resolving packages...
[2/4] 🚚   Fetching packages...
[3/4] 🔗   Linking dependencies...
warning "@klarna/higher-order-components@5.0.0" has incorrect peer dependency "prop-types@^15.5.10".
warning "@klarna/higher-order-components@5.0.0" has incorrect peer dependency "react@^15.5.0".
warning "@klarna/higher-order-components@5.0.0" has incorrect peer dependency "recompose@^0.23.4".
warning "react-context-props@2.2.0" has incorrect peer dependency "react@^15.5.0".
warning "react-addons-test-utils@15.4.2" has incorrect peer dependency "react-dom@^15.4.2".
warning "ajv-keywords@1.5.1" has unmet peer dependency "ajv@>=4.10.0".
[4/4] 📃   Building fresh packages...
[-/4] ⠂ waiting...
[2/4] ⠂ electron:     at Hash.Readable.push (_stream_readable.js:211:10)
[-/4] ⠂ waiting...
[4/4] ⠂ node-sass: c++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFI
error /Users/daniel/git/klarna/ui/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /Users/daniel/git/klarna/ui/node_modules/electron
Output:
/Users/daniel/git/klarna/ui/node_modules/electron/install.js:46
  throw err
  ^

Error: Generated checksum for "electron-v1.6.0-darwin-x64.zip" did not match expected checksum.
    at ChecksumMismatchError.ErrorWithFilename (/Users/daniel/git/klarna/ui/node_modules/sumchecker/build.js:41:124)
    at new ChecksumMismatchError (/Users/daniel/git/klarna/ui/node_modules/sumchecker/build.js:56:133)
    at Hash.<anonymous> (/Users/daniel/git/klarna/ui/node_modules/sumchecker/build.js:203:22)
    at emitNone (events.js:105:13)
    at Hash.emit (events.js:207:7)
    at emitReadable_ (_stream_readable.js:516:10)
    at emitReadable (_stream_readable.js:510:7)
```

Any clues why this is happening?

**Comment by moriaam** [comment]
remove node_modules and install it with node 6.
